#pragma config(Motor,  port1,           holo2,         tmotorVex269, openLoop)
#pragma config(Motor,  port2,           holo1,         tmotorVex269, openLoop)
#pragma config(Motor,  port3,           feed1,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           feed2,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           holo4,         tmotorVex269, openLoop)
#pragma config(Motor,  port6,           shootr1,       tmotorVex393, openLoop)
#pragma config(Motor,  port7,           shootr2,       tmotorVex393, openLoop)
#pragma config(Motor,  port8,           shootl1,       tmotorVex393, openLoop)
#pragma config(Motor,  port9,           shootl2,       tmotorVex393, openLoop)
#pragma config(Motor,  port10,          holo3,         tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*CAN WE WRITE INTERRUPTS IN THIS? Well I don't know the actual interrupt order for this so idk
Thought workspace: try it before I try the adding thing.*/
void alioop(void);
bool cupcake = false;

task main()
{
	int speed = 70;
	while(true)
	{
	 /*Driving Mechanisms : Holonomic Drive eventually*/
		motor[port1]= ((vexRT[Ch3]) + (vexRT[Ch4]) + (vexRT[Ch1]));//Fl
		motor[port2]= ((vexRT[Ch3]) - (vexRT[Ch4]) - (vexRT[Ch1]));//FR
		motor[port5]= (-(vexRT[Ch3]) - (vexRT[Ch4]) + (vexRT[Ch1]));//BR
		motor[port10]= (-(vexRT[Ch3]) + (vexRT[Ch4]) - (vexRT[Ch1]));//BL

		/*Shooting Mechanisms*/
		if(vexRT[Btn8D]==1)
		{
			alioop();
		}
		if(vexRT[Btn6U]==1 && speed<=120){
			speed=speed+5;
			wait10Msec(100);
		}
		else if(vexRT[Btn6D]==1 && speed>=50){
			speed=speed-5;
			wait10Msec(100);
	  }
	  else{
	  		speed=speed;
	  }
		if(cupcake==true)
		{
			motor[port6]=speed;
			motor[port7]=-speed;
			motor[port8]=speed;
			motor[port9]=-speed;
		}
		else
		{
			motor[port6]=0;
			motor[port7]=0;
			motor[port8]=0;
			motor[port9]=0;
		}
		/*Intake Mechanism*/
		if(vexRT[Btn5U]==1)
		{
			motor[port3]=120;
			motor[port4]=120;
		}
		else if(vexRT[Btn5D]==1)
		{
			motor[port3]=-120;
			motor[port4]=-120;
		}
		else
		{
			motor[port3]=0;
			motor[port4]=0;
		}
	}
}

void alioop(void){					// Switches variable to opposite value
	if(cupcake==false)cupcake=true;
	else cupcake=false;
	wait10Msec(100);
}
