#pragma config(Motor,  port1,           conquer,       tmotorVex269, openLoop)
#pragma config(Motor,  port2,           wimper,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           wimpel,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           repeattop,     tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           repeatbot,     tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,           shtop,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port7,           shbot,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port9,           ovenmitts,     tmotorVex269, openLoop)
#pragma config(Motor,  port10,          compel,        tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor(wimper) = vexRT(Ch2);
		motor(conquer) = -vexRT(Ch2);
		motor(compel) = vexRT(Ch3);
		motor(wimpel) = -vexRT(Ch3);

		if (vexRT(Btn8D)==1)
		{
			motor(ovenmitts)=-127;
		}
		else if (vexRT(Btn8R)==1)
		{
			motor(ovenmitts)=127;
		}
		else
		{
			motor(ovenmitts)=0;
		}

/*		if ((vexRT(Btn6U)==1)&&(SensorValue(burnt)==0))
		{
			motor(popup)=127;
			motor(popupagain)=-127;
		}
		else if (vexRT(Btn6D)==1)
		{
			motor(popup)=-127;
			motor(popupagain)=127;
		}
		else
		{
			motor(popup)=0;
			motor(popupagain)=0;
		}*/
		if ((vexRT(Btn5U)==1))
		{
			motor[port6]=127;
			motor[port7]=-127;
			motor[port5]=127;
			motor[port4]=127; // Why is this one also positive???
		}
		else if (vexRT(Btn5D)==1)
		{
			motor[port6]=-127;
			motor[port7]=127;
			motor[port5]=-127;
			motor[port4]=-127;
		}
		else
		{
			motor[port6]=0;
			motor[port7]=0;
			motor[port4]=0;
			motor[port5]=0;
		}
	}
}
